version: "3.8"

services:
  db:
    image: postgres:15
    container_name: sam_postgres
    restart: always
    ports:
      - "5432:5432" # Expose PostgreSQL on the host machine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sam_dev
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
